{
 "title": "F2B map (WIP)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Number of banned IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(client_id) FROM ban "
    }
   ]
  },
  {
   "title": "Total failed attempts (All jails)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(attempted_at) FROM attempt LIMIT 50 "
    }
   ]
  },
  {
   "title": "Bans/Attempts (All jails)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, COUNT(ip) AS \"attempt\" FROM client JOIN attempt ON client.id = attempt.client_id GROUP BY date "
    }
   ]
  },
  {
   "title": "Banned IPs locations",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT lat, lon, ip FROM client JOIN attempt ON client.id = attempt.client_id"
    },
    {
     "rawSql": "SELECT lat, lon, ip FROM client JOIN ban ON client.id = ban.client_id"
    }
   ]
  },
  {
   "title": "By countries",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT country, COUNT(ip) FROM client GROUP BY country ORDER BY COUNT(ip) DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Banned IPs",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT ip, country, isp, org, date FROM client JOIN ban ON client.id = ban.client_id ORDER BY date DESC LIMIT 50 "
    }
   ]
  }
 ]
}