services:

  postgresql:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres
    shm_size: 64mb
    mem_limit: 20m
    memswap_limit: 50m
    mem_swappiness: 20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      #   remain this only if you want a mongoDB to be accesible from your LAN
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  parse_log:
    mem_limit: 20m
    memswap_limit: 100m
    mem_swappiness: 20
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/log/fail2ban.log:/app/fail2ban.log
    restart: unless-stopped
  

  adminer:
    image: adminer
    mem_limit: 20m
    memswap_limit: 50m
    mem_swappiness: 80
    restart: unless-stopped
    ports:
      - 8080:8080
